#lang racket/base

(struct expr-const (val) #:transparent)
(struct expr-id (x) #:transparent)
(struct expr-binary (op lhs rhs) #:transparent)
(struct expr-unary (op val) #:transparent)
(struct expr-list (val) #:transparent)
(struct expr-hash (val) #:transparent)
(struct expr-set! (lhs rhs) #:transparent)
(struct expr-cond (pred then else) #:transparent)
(struct expr-prop (obj name) #:transparent)
(struct expr-verb (obj vdesc args) #:transparent)
(struct expr-call (fn args) #:transparent)
(struct expr-catch (try codes except) #:transparent)
(struct expr-error (type) #:transparent)

(provide (struct-out expr-const)
         (struct-out expr-id)
         (struct-out expr-binary)
         (struct-out expr-unary)
         (struct-out expr-list)
         (struct-out expr-hash)
         (struct-out expr-set!)
         (struct-out expr-cond)
         (struct-out expr-prop)
         (struct-out expr-verb)
         (struct-out expr-call)
         (struct-out expr-catch)
         (struct-out expr-error))